# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/walton/qcom-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/walton/qcom-common/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/walton/qcom-common/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/walton/qcom-common/proprietary/bin/dbvc_atvc_property_set:system/bin/dbvc_atvc_property_set \
    vendor/walton/qcom-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/walton/qcom-common/proprietary/bin/ftmipcd:system/bin/ftmipcd \
    vendor/walton/qcom-common/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/walton/qcom-common/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/walton/qcom-common/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/walton/qcom-common/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/walton/qcom-common/proprietary/bin/radish:system/bin/radish \
    vendor/walton/qcom-common/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/walton/qcom-common/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/walton/qcom-common/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/walton/qcom-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/walton/qcom-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/walton/qcom-common/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/walton/qcom-common/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/walton/qcom-common/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/walton/qcom-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/walton/qcom-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/walton/qcom-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/walton/qcom-common/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/walton/qcom-common/proprietary/lib/libOmxAmrwbplusDec.so:system/lib/libOmxAmrwbplusDec.so \
    vendor/walton/qcom-common/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/walton/qcom-common/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/walton/qcom-common/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/walton/qcom-common/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/walton/qcom-common/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/walton/qcom-common/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/walton/qcom-common/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/walton/qcom-common/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/walton/qcom-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/walton/qcom-common/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/walton/qcom-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/walton/qcom-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so
